### ISSUE TITLE
NPX setup in macos

### ISSUE THREAD

**Issue by shiyuwang-jamk** [snomiao/rime-snomiao#11]
`npx rime-snomiao@latest` copies the files to ~/Library/Rime/Rime

Is this setup on purpose?

**Comment by snomiao** [comment]
no

**Comment by snomiao** [comment]
cou u make a pr to fix this? should be sth wrong in cli.ts

**Comment by shiyuwang-jamk** [comment]
> cou u make a pr to fix this? should be sth wrong in cli.ts

Where is the current directory `.` at line 27 after the first cp? I am confused and I do not know how I can run tests myself.
https://github.com/snomiao/rime-snomiao/blob/f7e39d4a07ea87c793991312145fde1714e77e66/src/cli.ts#L27

**Comment by snomiao** [comment]
rime-snomiao/*
-->
rime-snomiao/Rime/*

**Comment by snomiao** [comment]
merged
