### ISSUE TITLE
如何实现 F7 直接输出片假名

### ISSUE THREAD

**Issue by Explorare** [snomiao/rime-snomiao#5]
Win10 的 IME 可以在输入状态时用 F6~F10 输出指定格式，平假名、片假名、半角片假名、全角大小写英文，在输入词典里不存在的人名的情况下很方便。不知 RIME 里能否实现此功能。

**Comment by ZHUOYIDONG** [comment]
@Explorare 

目前rime提供のapi倒是可以做詞典开关。

理論估計需要先按F6-F10，然後再選词再空格或者回车之類。

你可以尝试把按键和詞典对因关系列在这个issue里

F6：平仮名 ON-OFF
F7：片仮名
F....

谁有其他思路也可以补充在这里

**Comment by Explorare** [comment]
谢谢回复，我在 RIME 的 repo [提问](https://github.com/hchunhui/librime-lua/issues/126)得到回复，发现已经有相关讨论了，而且也提供了具体的思路。
[能加优化一下lua 加个能切换指定方案的方法么？ · Issue #126 · hchunhui/librime-lua](https://github.com/hchunhui/librime-lua/issues/126)
我先关闭这个 issue，之后会在上面的 issue 继续研究。谢谢。
